package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAluno;
import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import javax.swing.JOptionPane;

public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiCurso
     */
    public GuiAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLblCPF = new javax.swing.JLabel();
        formatCPF = new javax.swing.JFormattedTextField();
        jLblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLblSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        jLblEstadoCivil = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        jLblEscolaridade = new javax.swing.JLabel();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        jLblEndereco = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLblBairro = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLblRG = new javax.swing.JLabel();
        jLblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLblNoEndereco = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLblCEP = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLblTelRes = new javax.swing.JLabel();
        jLblCelular = new javax.swing.JLabel();
        formatCEP = new javax.swing.JFormattedTextField();
        formatTelefone = new javax.swing.JFormattedTextField();
        formatCelular = new javax.swing.JFormattedTextField();
        formatRG = new javax.swing.JFormattedTextField();
        jLblDataNascto = new javax.swing.JLabel();
        formatDataNasc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Aluno");
        setPreferredSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLblCPF.setText("CPF");

        try {
            formatCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblNome.setText("Nome");

        txtNome.setEnabled(false);

        jLblSexo.setText("Sexo");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        cbxSexo.setEnabled(false);

        jLblEstadoCivil.setText("Estado Civil");

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Solteiro" }));
        cbxEstadoCivil.setEnabled(false);

        jLblEscolaridade.setText("Escolaridade");

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior" }));
        cbxEscolaridade.setEnabled(false);

        jLblEndereco.setText("Endereço");

        txtBairro.setEnabled(false);

        jLblBairro.setText("Bairro");

        txtEndereco.setEnabled(false);

        jLblCidade.setText("Cidade");

        txtCidade.setEnabled(false);

        jLblRG.setText("RG");

        jLblEmail.setText("Email");

        txtEmail.setEnabled(false);

        jLblNoEndereco.setText("Nº");

        txtNumero.setEnabled(false);

        jLblCEP.setText("CEP");

        jLblEstado.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbxEstado.setEnabled(false);

        jLblTelRes.setText("Tel. Res");

        jLblCelular.setText("Celular");

        try {
            formatCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCEP.setEnabled(false);

        try {
            formatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatTelefone.setEnabled(false);

        try {
            formatCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCelular.setEnabled(false);

        try {
            formatRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatRG.setEnabled(false);

        jLblDataNascto.setText("Data Nascto.");

        try {
            formatDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataNasc.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formatCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblRG)
                            .addComponent(jLblEmail)
                            .addComponent(jLblSexo)
                            .addComponent(jLblEndereco)
                            .addComponent(jLblBairro)
                            .addComponent(jLblCPF)
                            .addComponent(jLblNome)
                            .addComponent(jLblCidade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jLblDataNascto))
                                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(formatCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLblEstadoCivil)
                                .addGap(18, 18, 18)
                                .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLblEscolaridade)
                                .addGap(18, 18, 18)
                                .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(383, 383, 383)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLblNoEndereco)
                                                .addComponent(jLblCEP))
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLblCelular)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(49, 49, 49)
                                                    .addComponent(jLblTelRes)))
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(formatRG, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(293, 293, 293)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formatTelefone)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formatCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCPF)
                    .addComponent(formatCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataNascto)
                    .addComponent(formatDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSexo)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstadoCivil)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEscolaridade)
                    .addComponent(cbxEscolaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNoEndereco)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBairro)
                    .addComponent(jLblCEP)
                    .addComponent(formatCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCidade)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstado)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTelRes)
                    .addComponent(formatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRG)
                    .addComponent(jLblCelular)
                    .addComponent(formatCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Cadastar Aluno");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        aluno = null;
        if (Pessoa.validarCPF(formatCPF.getText().replaceAll("[.,-]", ""))) {
            aluno = daoAluno.consultar(formatCPF.getText().replaceAll("[.,-]", ""));
            if (aluno == null) {
                btnInserir.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
            } else {
                txtNome.setText(aluno.getNome());
                formatDataNasc.setText(aluno.getDataNasc());
                cbxSexo.setSelectedItem(aluno.getSexo());
                cbxEstadoCivil.setSelectedItem(aluno.getEstadoCivil());
                cbxEscolaridade.setSelectedItem(aluno.getEscolaridade());
                txtEndereco.setText(aluno.getEndereco());
                txtNumero.setText(Integer.toString(aluno.getNumero()));
                txtBairro.setText(aluno.getBairro());
                formatCEP.setText(aluno.getCpf());
                txtCidade.setText(aluno.getCidade());
                cbxEstado.setSelectedItem(aluno.getEstado());
                formatTelefone.setText(aluno.getTelefone());
                formatRG.setText(aluno.getRg());
                formatCelular.setText(aluno.getCelular());
                txtEmail.setText(aluno.getEmail());

                btnInserir.setEnabled(false);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
            formatCPF.setEnabled(false);
            txtNome.setEnabled(true);
            txtNome.requestFocus();
            formatDataNasc.setEnabled(true);
            cbxSexo.setEnabled(true);
            cbxEstadoCivil.setEnabled(true);
            cbxEscolaridade.setEnabled(true);
            txtEndereco.setEnabled(true);
            txtNumero.setEnabled(true);
            txtBairro.setEnabled(true);
            formatCEP.setEnabled(true);
            txtCidade.setEnabled(true);
            cbxEstado.setEnabled(true);
            formatTelefone.setEnabled(true);
            formatRG.setEnabled(true);
            formatCelular.setEnabled(true);
            txtEmail.setEnabled(true);
            cbxSexo.setSelectedIndex(0);
            cbxEstadoCivil.setSelectedIndex(0);
            cbxEscolaridade.setSelectedIndex(0);
            cbxEstado.setSelectedIndex(0);

            btnConsultar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD1811019", "BD1811019");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");
        daoAluno = new DaoAluno(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        aluno = new Aluno(txtNome.getText(), formatCPF.getText().replaceAll("[.,-]", ""));
        aluno.setDataNasc(formatDataNasc.getText());
        aluno.setSexo(cbxSexo.getSelectedItem().toString());
        aluno.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
        aluno.setEscolaridade(cbxEscolaridade.getSelectedItem().toString());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setNumero(Integer.parseInt(txtNumero.getText()));
        aluno.setBairro(txtBairro.getText());
        aluno.setCep(formatCEP.getText().replaceAll("[.,-]", ""));
        aluno.setCidade(txtCidade.getText());
        aluno.setEstado(cbxEstado.getSelectedItem().toString());
        aluno.setTelefone(formatTelefone.getText().replaceAll("[),(,.,-]", ""));
        aluno.setRg(formatRG.getText().replaceAll("[.,-]", ""));
        aluno.setCelular(formatCelular.getText().replaceAll("[),(,.,-]", ""));
        aluno.setEmail(txtEmail.getText());

        daoAluno.inserir(aluno);

        formatCPF.setText("");
        txtNome.setText("");
        formatDataNasc.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        formatCEP.setText("");
        txtCidade.setText("");
        formatTelefone.setText("");
        formatRG.setText("");
        formatCelular.setText("");
        txtEmail.setText("");

        formatCPF.setEnabled(true);
        formatCPF.requestFocus();
        txtNome.setEnabled(false);
        formatDataNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        formatCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        formatTelefone.setEnabled(false);
        formatRG.setEnabled(false);
        formatCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        cbxSexo.setSelectedIndex(0);
        cbxEstadoCivil.setSelectedIndex(0);
        cbxEscolaridade.setSelectedIndex(0);
        cbxEstado.setSelectedIndex(0);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
            aluno.setNome(txtNome.getText());
            aluno.setDataNasc(formatDataNasc.getText());
            aluno.setSexo(cbxSexo.getSelectedItem().toString());
            aluno.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
            aluno.setEscolaridade(cbxEscolaridade.getSelectedItem().toString());
            aluno.setEndereco(txtEndereco.getText());
            aluno.setNumero(Integer.parseInt(txtNumero.getText()));
            aluno.setBairro(txtBairro.getText());
            aluno.setCep(formatCEP.getText().replaceAll("[.,-]", ""));
            aluno.setCidade(txtCidade.getText());
            aluno.setEstado(cbxEstado.getSelectedItem().toString());
            aluno.setTelefone(formatTelefone.getText().replaceAll("[),(,.,-]", ""));
            aluno.setRg(formatRG.getText().replaceAll("[.,-]", ""));
            aluno.setCelular(formatCelular.getText().replaceAll("[),(,.,-]", ""));
            aluno.setEmail(txtEmail.getText());

            daoAluno.alterar(aluno);
        }
        formatCPF.setText("");
        txtNome.setText("");
        formatDataNasc.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        formatCEP.setText("");
        txtCidade.setText("");
        formatTelefone.setText("");
        formatRG.setText("");
        formatCelular.setText("");
        txtEmail.setText("");

        formatCPF.setEnabled(true);
        formatCPF.requestFocus();
        txtNome.setEnabled(false);
        formatDataNasc.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);
        txtBairro.setEnabled(false);
        formatCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        formatTelefone.setEnabled(false);
        formatRG.setEnabled(false);
        formatCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        cbxSexo.setSelectedIndex(0);
        cbxEstadoCivil.setSelectedIndex(0);
        cbxEscolaridade.setSelectedIndex(0);
        cbxEstado.setSelectedIndex(0);
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclsão?") == 0) {
            daoAluno.excluir(aluno);

            formatCPF.setText("");
            txtNome.setText("");
            formatDataNasc.setText("");
            txtEndereco.setText("");
            txtNumero.setText("");
            txtBairro.setText("");
            formatCEP.setText("");
            txtCidade.setText("");
            formatTelefone.setText("");
            formatRG.setText("");
            formatCelular.setText("");
            txtEmail.setText("");

            formatCPF.setEnabled(true);
            formatCPF.requestFocus();
            txtNome.setEnabled(false);
            formatDataNasc.setEnabled(false);
            cbxSexo.setEnabled(false);
            cbxEstadoCivil.setEnabled(false);
            cbxEscolaridade.setEnabled(false);
            txtEndereco.setEnabled(false);
            txtNumero.setEnabled(false);
            txtBairro.setEnabled(false);
            formatCEP.setEnabled(false);
            txtCidade.setEnabled(false);
            cbxEstado.setEnabled(false);
            formatTelefone.setEnabled(false);
            formatRG.setEnabled(false);
            formatCelular.setEnabled(false);
            txtEmail.setEnabled(false);
            cbxSexo.setSelectedIndex(0);
            cbxEstadoCivil.setSelectedIndex(0);
            cbxEscolaridade.setSelectedIndex(0);
            cbxEstado.setSelectedIndex(0);

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JFormattedTextField formatCEP;
    private javax.swing.JFormattedTextField formatCPF;
    private javax.swing.JFormattedTextField formatCelular;
    private javax.swing.JFormattedTextField formatDataNasc;
    private javax.swing.JFormattedTextField formatRG;
    private javax.swing.JFormattedTextField formatTelefone;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCEP;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCelular;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblDataNascto;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblEscolaridade;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblEstadoCivil;
    private javax.swing.JLabel jLblNoEndereco;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblRG;
    private javax.swing.JLabel jLblSexo;
    private javax.swing.JLabel jLblTelRes;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
    private DaoAluno daoAluno = null;
    private Aluno aluno = null;
    private Conexao conexao = null;
}
