package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoAPrazo;
import fatec.poo.control.DaoAVista;
import fatec.poo.control.DaoAluno;
import fatec.poo.control.DaoCurso;
import fatec.poo.control.DaoMatricula;
import fatec.poo.control.DaoTurma;
import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class GuiEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiEfetuarMatricula
     */
    public GuiEfetuarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fprBtnPagamento = new javax.swing.ButtonGroup();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLblDataMatricula = new javax.swing.JLabel();
        formatDataMatricula = new javax.swing.JFormattedTextField();
        jLblCurso = new javax.swing.JLabel();
        cbxCurso = new javax.swing.JComboBox<>();
        cbxTurma = new javax.swing.JComboBox<>();
        jLblTurma = new javax.swing.JLabel();
        jLblCPF = new javax.swing.JLabel();
        formatCPF = new javax.swing.JFormattedTextField();
        jLblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLblNome = new javax.swing.JLabel();
        jPnlPagamento = new javax.swing.JPanel();
        radBtnAVista = new javax.swing.JRadioButton();
        radBtnParcelado = new javax.swing.JRadioButton();
        jLblDataVencimento = new javax.swing.JLabel();
        formatDataVencimento = new javax.swing.JFormattedTextField();
        formatDataPagamento = new javax.swing.JFormattedTextField();
        jLblDataPagamento = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        jLblAgencia = new javax.swing.JLabel();
        formatQtdeMensalidades = new javax.swing.JTextField();
        jLblQtdeMensalidades = new javax.swing.JLabel();
        jLblNumCheque = new javax.swing.JLabel();
        txtNumCheque = new javax.swing.JTextField();
        jLblTaxaJuros = new javax.swing.JLabel();
        txtTaxaJuros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Efetuar Matrícula");
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLblDataMatricula.setText("Data Matrícula");

        try {
            formatDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblCurso.setText("Curso");

        cbxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursoActionPerformed(evt);
            }
        });

        cbxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTurmaActionPerformed(evt);
            }
        });

        jLblTurma.setText("Turma");

        jLblCPF.setText("CPF Aluno");

        try {
            formatCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCPF.setEnabled(false);

        jLblValor.setText("Valor R$");

        txtValor.setEditable(false);

        txtNome.setEditable(false);

        jLblNome.setText("Nome");

        jPnlPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        fprBtnPagamento.add(radBtnAVista);
        radBtnAVista.setText("À Vista");
        radBtnAVista.setEnabled(false);
        radBtnAVista.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radBtnAVistaStateChanged(evt);
            }
        });

        fprBtnPagamento.add(radBtnParcelado);
        radBtnParcelado.setText("Parcelado");
        radBtnParcelado.setEnabled(false);
        radBtnParcelado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radBtnParceladoStateChanged(evt);
            }
        });

        jLblDataVencimento.setText("Data 1º Vencto.");

        try {
            formatDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataVencimento.setEnabled(false);

        try {
            formatDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatDataPagamento.setEnabled(false);

        jLblDataPagamento.setText("Data Pagto.");

        txtAgencia.setEnabled(false);

        jLblAgencia.setText("Agência");

        formatQtdeMensalidades.setEnabled(false);

        jLblQtdeMensalidades.setText("Qtde. Mensalidades");

        jLblNumCheque.setText("No. Cheque");

        txtNumCheque.setEnabled(false);

        jLblTaxaJuros.setText("Tx. Juros(%)");

        txtTaxaJuros.setEnabled(false);

        javax.swing.GroupLayout jPnlPagamentoLayout = new javax.swing.GroupLayout(jPnlPagamento);
        jPnlPagamento.setLayout(jPnlPagamentoLayout);
        jPnlPagamentoLayout.setHorizontalGroup(
            jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnAVista)
                    .addComponent(radBtnParcelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblAgencia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblQtdeMensalidades, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatQtdeMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNumCheque)
                    .addComponent(jLblTaxaJuros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblDataPagamento)
                    .addComponent(jLblDataVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formatDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPnlPagamentoLayout.setVerticalGroup(
            jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPagamentoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(formatDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNumCheque)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAgencia)
                    .addComponent(radBtnAVista))
                .addGap(30, 30, 30)
                .addGroup(jPnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(radBtnParcelado)
                    .addComponent(jLblQtdeMensalidades)
                    .addComponent(formatQtdeMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaxaJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDataVencimento)
                    .addComponent(formatDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLblCPF)
                                .addComponent(jLblDataMatricula))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblCurso)
                                    .addComponent(jLblTurma))
                                .addGap(41, 41, 41)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formatCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jLblNome)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLblValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(formatDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblDataMatricula)
                    .addComponent(formatDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCurso)
                    .addComponent(jLblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTurma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLblCPF)
                    .addComponent(formatCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnInserir)
                    .addComponent(btnConsultar))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        avista = null;
        aprazo = null;
        turma = daoTurma.consultar(cbxTurma.getSelectedItem().toString());

        if (radBtnAVista.isSelected()) {
            avista = new AVista();
            avista.setValor(Double.parseDouble(txtValor.getText()));
            avista.setAgencia(Integer.parseInt(txtAgencia.getText()));
            avista.setPreData(formatDataPagamento.getText());
            avista.setnCheque(Integer.parseInt(txtNumCheque.getText()));
            daoAVista.inserir(avista);
        } else {
            aprazo = new APrazo();
            aprazo.setValor(Double.parseDouble(txtValor.getText()));
            aprazo.setQtdeMensalidade(Integer.parseInt(formatQtdeMensalidades.getText()));
            aprazo.setTaxaJuros(Double.parseDouble(txtTaxaJuros.getText()));
            aprazo.setDtVencimento(formatDataVencimento.getText());
            daoAPrazo.inserir(aprazo);
        }
        matricula = new Matricula(formatDataMatricula.getText());
        matricula.setAluno(daoAluno.consultar(formatCPF.getText().replaceAll("[.,-]", "")));
        matricula.setaPrazo(aprazo);
        matricula.setaVista(avista);
        turma.addMatricula(matricula);
        daoMatricula.inserir(matricula);

        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnInserir.setEnabled(false);
        cbxCurso.setEnabled(true);
        cbxTurma.setEnabled(true);
        cbxCurso.setSelectedIndex(0);
        formatDataMatricula.setText("");
        formatDataMatricula.setEnabled(true);
        formatDataMatricula.requestFocus();
        txtNome.setText("");
        formatCPF.setText("");
        formatCPF.setEnabled(false);
        
        
        radBtnAVista.setSelected(false);
        radBtnAVista.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtAgencia.setText("");
        txtNumCheque.setEnabled(false);
        txtNumCheque.setText("");
        formatDataPagamento.setEnabled(false);
        formatDataPagamento.setText("");
        
        radBtnParcelado.setSelected(false);
        radBtnParcelado.setEnabled(false);
        formatQtdeMensalidades.setEnabled(false);
        formatQtdeMensalidades.setText("");
        txtTaxaJuros.setEnabled(false);
        txtTaxaJuros.setText("");
        formatDataVencimento.setEnabled(false);
        formatDataVencimento.setText("");
        
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {
            if (radBtnAVista.isSelected()) {
                if (matricula.getaVista() == null) {
                    avista = new AVista();
                    avista.setValor(Double.parseDouble(txtValor.getText()));
                    avista.setAgencia(Integer.parseInt(txtAgencia.getText()));
                    avista.setPreData(formatDataPagamento.getText());
                    avista.setnCheque(Integer.parseInt(txtNumCheque.getText()));
                    
                    daoAVista.inserir(avista);
                    matricula.setaVista(avista);
                    aprazo = matricula.getaPrazo();
                    matricula.setaPrazo(null);
                    daoMatricula.alterar(matricula);
                    daoAPrazo.excluir(aprazo);
                } else {
                    matricula.getaVista().setAgencia(Integer.parseInt(txtAgencia.getText()));
                    matricula.getaVista().setPreData(formatDataPagamento.getText());
                    matricula.getaVista().setnCheque(Integer.parseInt(txtNumCheque.getText()));
                    daoAVista.alterar(matricula.getaVista());
                    daoMatricula.alterar(matricula);
                }
            } else {
                if (matricula.getaPrazo() == null) {
                    aprazo = new APrazo();
                    aprazo.setValor(Double.parseDouble(txtValor.getText()));
                    aprazo.setQtdeMensalidade(Integer.parseInt(formatQtdeMensalidades.getText()));
                    aprazo.setTaxaJuros(Double.parseDouble(txtTaxaJuros.getText()));
                    aprazo.setDtVencimento(formatDataVencimento.getText());
                    
                    daoAPrazo.inserir(aprazo);
                    matricula.setaPrazo(aprazo);
                    avista = matricula.getaVista();
                    matricula.setaVista(null);
                    daoMatricula.alterar(matricula);
                    daoAVista.excluir(avista);
                } else {
                    matricula.getaPrazo().setQtdeMensalidade(Integer.parseInt(formatQtdeMensalidades.getText()));
                    matricula.getaPrazo().setTaxaJuros(Double.parseDouble(txtTaxaJuros.getText()));
                    matricula.getaPrazo().setDtVencimento(formatDataVencimento.getText());
                    daoAPrazo.alterar(matricula.getaPrazo());
                    daoMatricula.alterar(matricula);
                }                
            }
        }
btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnInserir.setEnabled(false);
        cbxCurso.setEnabled(true);
        cbxTurma.setEnabled(true);
        cbxCurso.setSelectedIndex(0);
        formatDataMatricula.setText("");
        formatDataMatricula.setEnabled(true);
        formatDataMatricula.requestFocus();
        txtNome.setText("");
        formatCPF.setText("");
        formatCPF.setEnabled(false);
        
        
        radBtnAVista.setSelected(false);
        radBtnAVista.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtAgencia.setText("");
        txtNumCheque.setEnabled(false);
        txtNumCheque.setText("");
        formatDataPagamento.setEnabled(false);
        formatDataPagamento.setText("");
        
        radBtnParcelado.setSelected(false);
        radBtnParcelado.setEnabled(false);
        formatQtdeMensalidades.setEnabled(false);
        formatQtdeMensalidades.setText("");
        txtTaxaJuros.setEnabled(false);
        txtTaxaJuros.setText("");
        formatDataVencimento.setEnabled(false);
        formatDataVencimento.setText("");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        aluno = null;
        matricula = null;

        if (Pessoa.validarCPF(formatCPF.getText().replaceAll("[.,-]", ""))) {
            matricula = daoMatricula.consultar(formatCPF.getText().replaceAll("[.,-]", ""));
            aluno = daoAluno.consultar(formatCPF.getText().replaceAll("[.,-]", ""));
            if (aluno != null) {
                txtNome.setText(aluno.getNome());
                formatCPF.setEnabled(false);
                cbxCurso.setEnabled(false);
                cbxTurma.setEnabled(false);
                btnConsultar.setEnabled(false);
                if (matricula == null) {
                    btnAlterar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    btnInserir.setEnabled(true);
                } else {
                    btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                    btnInserir.setEnabled(false);
                    formatDataMatricula.setText(matricula.getData());
                    formatDataMatricula.setEnabled(false);

                    turma = daoTurma.consultar(matricula.getTurma().getSiglaTurma());
                    curso = daoCurso.consultar(turma.getCurso().getSigla());
                    cbxCurso.setSelectedItem(curso.getSigla());
                    cbxTurma.setSelectedItem(turma.getSiglaTurma());

                    if (matricula.getaVista() == null) {
                        radBtnParcelado.setSelected(true);
                        formatQtdeMensalidades.setText(String.valueOf(matricula.getaPrazo().getQtdeMensalidade()));
                        txtTaxaJuros.setText(String.valueOf(matricula.getaPrazo().getTaxaJuros()));
                        formatDataVencimento.setText(matricula.getaPrazo().getDtVencimento());
                    } else {
                        radBtnAVista.setSelected(true);
                        txtAgencia.setText(String.valueOf(matricula.getaVista().getAgencia()));
                        txtNumCheque.setText(String.valueOf(matricula.getaVista().getnCheque()));
                        formatDataPagamento.setText(matricula.getaVista().getPreData());
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Aluno não cadastrado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF Inválido");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Exclsão?") == 0) {
            daoMatricula.excluir(matricula);
            matricula.getAluno().setMatricula(null);
            matricula.getTurma().remMatricula(matricula);
            matricula.setaPrazo(null);
            matricula.setaVista(null);
            
            btnConsultar.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnInserir.setEnabled(false);
            cbxCurso.setEnabled(true);
            cbxTurma.setEnabled(true);
            cbxCurso.setSelectedIndex(0);
            formatDataMatricula.setText("");
            formatDataMatricula.setEnabled(true);
            formatDataMatricula.requestFocus();
            txtNome.setText("");
            formatCPF.setText("");
            formatCPF.setEnabled(false);


            radBtnAVista.setSelected(false);
            radBtnAVista.setEnabled(false);
            txtAgencia.setEnabled(false);
            txtAgencia.setText("");
            txtNumCheque.setEnabled(false);
            txtNumCheque.setText("");
            formatDataPagamento.setEnabled(false);
            formatDataPagamento.setText("");

            radBtnParcelado.setSelected(false);
            radBtnParcelado.setEnabled(false);
            formatQtdeMensalidades.setEnabled(false);
            formatQtdeMensalidades.setText("");
            txtTaxaJuros.setEnabled(false);
            txtTaxaJuros.setText("");
            formatDataVencimento.setEnabled(false);
            formatDataVencimento.setText("");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD1811019", "BD1811019");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");
        daoCurso = new DaoCurso(conexao.conectar());
        daoMatricula = new DaoMatricula(conexao.conectar());
        daoTurma = new DaoTurma(conexao.conectar());
        daoAluno = new DaoAluno(conexao.conectar());
        daoAVista = new DaoAVista(conexao.conectar());
        daoAPrazo = new DaoAPrazo(conexao.conectar());

        cursos = daoCurso.listarCursos();

        for (Curso i : cursos) {
            cbxCurso.addItem(i.getSigla());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cbxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTurmaActionPerformed
        if (cbxTurma.isEnabled()) {
            if (cbxTurma.getSelectedItem() != null) {
                formatCPF.setEnabled(true);
                radBtnAVista.setEnabled(true);
                radBtnParcelado.setEnabled(true);
            } else {
                radBtnAVista.setSelected(false);
                radBtnAVista.setEnabled(false);
                txtAgencia.setEnabled(false);
                txtAgencia.setText("");
                txtNumCheque.setEnabled(false);
                txtNumCheque.setText("");
                formatDataPagamento.setEnabled(false);
                formatDataPagamento.setText("");

                radBtnParcelado.setSelected(false);
                radBtnParcelado.setEnabled(false);
                formatQtdeMensalidades.setEnabled(false);
                formatQtdeMensalidades.setText("");
                txtTaxaJuros.setEnabled(false);
                txtTaxaJuros.setText("");
                formatDataVencimento.setEnabled(false);
                formatDataVencimento.setText("");
            }
        }
    }//GEN-LAST:event_cbxTurmaActionPerformed

    private void radBtnAVistaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radBtnAVistaStateChanged
        if (radBtnAVista.isSelected()) {
            txtAgencia.setEnabled(true);
            txtNumCheque.setEnabled(true);
            formatDataPagamento.setEnabled(true);
        } else {
            txtAgencia.setEnabled(false);
            txtAgencia.setText("");
            txtNumCheque.setEnabled(false);
            txtNumCheque.setText("");
            formatDataPagamento.setEnabled(false);
            formatDataPagamento.setText("");
        }
    }//GEN-LAST:event_radBtnAVistaStateChanged

    private void radBtnParceladoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radBtnParceladoStateChanged
        if (radBtnParcelado.isSelected()) {
            formatQtdeMensalidades.setEnabled(true);
            txtTaxaJuros.setEnabled(true);
            formatDataVencimento.setEnabled(true);
        } else {
            formatQtdeMensalidades.setEnabled(false);
            formatQtdeMensalidades.setText("");
            txtTaxaJuros.setEnabled(false);
            txtTaxaJuros.setText("");
            formatDataVencimento.setEnabled(false);
            formatDataVencimento.setText("");
        }
    }//GEN-LAST:event_radBtnParceladoStateChanged

    private void cbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoActionPerformed
        curso = cursos.get(cbxCurso.getSelectedIndex());
        txtValor.setText(String.valueOf(curso.getValor()));
        cbxTurma.removeAllItems();
        turmas = daoTurma.listarTurmasCurso(curso.getSigla());
        for (Turma i : turmas) {
            cbxTurma.addItem(i.getSiglaTurma());
        }
    }//GEN-LAST:event_cbxCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEfetuarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEfetuarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JFormattedTextField formatCPF;
    private javax.swing.JFormattedTextField formatDataMatricula;
    private javax.swing.JFormattedTextField formatDataPagamento;
    private javax.swing.JFormattedTextField formatDataVencimento;
    private javax.swing.JTextField formatQtdeMensalidades;
    private javax.swing.ButtonGroup fprBtnPagamento;
    private javax.swing.JLabel jLblAgencia;
    private javax.swing.JLabel jLblCPF;
    private javax.swing.JLabel jLblCurso;
    private javax.swing.JLabel jLblDataMatricula;
    private javax.swing.JLabel jLblDataPagamento;
    private javax.swing.JLabel jLblDataVencimento;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblNumCheque;
    private javax.swing.JLabel jLblQtdeMensalidades;
    private javax.swing.JLabel jLblTaxaJuros;
    private javax.swing.JLabel jLblTurma;
    private javax.swing.JLabel jLblValor;
    private javax.swing.JPanel jPnlPagamento;
    private javax.swing.JRadioButton radBtnAVista;
    private javax.swing.JRadioButton radBtnParcelado;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumCheque;
    private javax.swing.JTextField txtTaxaJuros;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private DaoMatricula daoMatricula = null;
    private DaoTurma daoTurma = null;
    private DaoCurso daoCurso = null;
    private DaoAluno daoAluno = null;
    private DaoAVista daoAVista = null;
    private DaoAPrazo daoAPrazo = null;
    private Conexao conexao = null;
    private Aluno aluno = null;
    private Curso curso = null;
    private Matricula matricula = null;
    private Turma turma = null;
    private APrazo aprazo = null;
    private AVista avista = null;
    ArrayList<Curso> cursos;
    ArrayList<Turma> turmas;
}
